server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/momopet
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # 추가
    defer-datasource-initialization: true # 추가
    hibernate:
      ddl-auto: create # application 실행 시점에 가지고 있는 Entity 정보를 보고 테이블을 모두 지우고 재생성
#      ddl-auto: none # 테이블 자동 삭제 및 생성 막음
    properties:
      hibernate:
#        show_sql: true # log에 출력되는 것이 아니라 sysout에 출력 됨
        format_sql: true
  # OAuth
  profiles:
    include: oauth # application-oauth.yml 을 참조 함

  # Session Store
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always # 항상 스키마 초기화

  # OAuth
  profiles:
    include:
      - oauth # application-oauth.yml 을 참조
      - aws # AWS S3 보안 파일 참조

  # Session Store
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always # 항상 스키마 초기화

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
